//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class App1Entities : DbContext
    {
        static private App1Entities _context;
        public App1Entities()
            : base("name=App1Entities")
        {
        }

        static public App1Entities GetContext()
        {
            if (_context == null)
                _context = new App1Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<ResidentialComplex> ResidentialComplex { get; set; }
    }
}
